### ISSUE TITLE
Stop hardcoding name of output

### ISSUE THREAD

**Issue by gaperez64** [mvcisback/py-aiger-dfa#2]
https://github.com/mvcisback/py-aiger-dfa/blob/3ad99def635c1a95d79a92663fe06da949ab75cb/aiger_dfa/aig2dfa.py#L66

I think it would be better to check whether the output is really called "output" here. I understand some assumptions need to be made about the sequential circuit being loaded, but maybe checking there is a unique output is enough? To see why it's an issue, try loading a sequential circuit (with an output named anything but "output") into a DFA and then dumping it to a dot file to get an error.

**Comment by mvcisback** [comment]
Thanks. I will take a look into this.

**Comment by mvcisback** [comment]
@gaperez64 Sorry for the delay. 

This should be implemented in 0.4.3

**Comment by mvcisback** [comment]
For some additional context,

`output` is still the fall back for backwards compatibility with #1.

But if a single output is provided, it will be used (assuming `output_name` isn't explicitly given at which point I wan't to cause an error if the outputs don't match).
